### PR TITLE
Fix webui installation spec test

### PR DESCRIPTION
**Pull request by shortdudey123**
Since the ConsulInstallationWebui provider relies on non-core chef resources, we can't use an inline recipe.

```
1) ConsulCookbook::Provider::ConsulInstallationWebui webui installation
 Failure/Error:
   it do is_expected.to unzip_zipfile('consul_0.6.4_web_ui.zip')
     .with(source: 'https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_web_ui.zip',
           path: '/opt/consul-webui/0.6.4')
   end

 NoMethodError:
   consul_installation[0.6.4] (/Users/user/github/chef-consul/test/spec/libraries/consul_installation_webui_spec.rb line 12) had an error: NoMethodError: No resource or method named `zipfile' for `ConsulCookbook::Provider::ConsulInstallationWebui ""'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/dsl/recipe.rb:102:in `rescue in method_missing'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/dsl/recipe.rb:99:in `method_missing'
 # ./libraries/consul_installation_webui.rb:50:in `block in action_create'
 # ./libraries/consul_installation_webui.rb:45:in `action_create'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/provider.rb:144:in `run_action'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/resource.rb:596:in `run_action'
 # ./.bundle/ruby/2.2.0/gems/chefspec-4.6.0/lib/chefspec/extensions/chef/resource.rb:22:in `run_action'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/runner.rb:73:in `run_action'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `block (2 levels) in converge'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `each'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `block in converge'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/runner.rb:104:in `converge'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/client.rb:668:in `block in converge'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/client.rb:663:in `catch'
 # ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/client.rb:663:in `converge'
 # ./.bundle/ruby/2.2.0/gems/chefspec-4.6.0/lib/chefspec/solo_runner.rb:126:in `converge'
 # ./test/spec/libraries/consul_installation_webui_spec.rb:17:in `block (3 levels) in <top (required)>'
 # ------------------
 # --- Caused by: ---
 # NoMethodError:
 #   undefined method `zipfile' for #<ConsulCookbook::Provider::ConsulInstallationWebui:0x007fc246a8ee80>
 #   ./.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/dsl/recipe.rb:100:in `method_missing'
```

### CODE REVIEW

**Comment by Ginja** [comment]
@johnbellone @shortdudey123 

This error during the CI test:

```
ArgumentError
-------------
Validation map has unknown check: name_property
```

Should be fixed with this PR johnbellone/rubyzip-cookbook#4

**Comment by shortdudey123** [comment]
@Ginja thanks! i hadn't had a chance to look at that yet error yet

**Comment by johnbellone** [comment]
I am wondering why these tests are passing locally for me. I just ran the build again for this pull-request and it threw an error about `nssm[consul]` not being in the resource collection. It looks like that we are guarding against that being installed a subsequent time.

**Comment by shortdudey123** [comment]
@johnbellone i am guessing you have something cached

if you clone the repo again, bundle install, and test... do they pass?

**Comment by shortdudey123** [comment]
This is the tests running locally for me
```
$ bundle exec rake unit
WARNING: Nokogiri was built against LibXML version 2.9.0, but has dynamically loaded 2.9.3
/usr/local/var/rbenv/versions/2.2.2/bin/ruby -I/Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/rspec-core-3.4.4/lib:/Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/rspec-support-3.4.1/lib /Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/rspec-core-3.4.4/exe/rspec --pattern test/spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 60655
...[2016-03-23T17:22:41-07:00] WARN: Default value {"PATH"=>"/usr/local/bin:/usr/bin:/bin"} is invalid for property environment. In Chef 13 this will become an error: Option environment must be a kind of [String]!  You passed {"PATH"=>"/usr/local/bin:/usr/bin:/bin"}.. at /Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/poise-2.6.0/lib/poise/helpers/lazy_default.rb:57:in `set_or_return' at /Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
.[2016-03-23T17:22:42-07:00] WARN: Default value {"PATH"=>"/usr/local/bin:/usr/bin:/bin"} is invalid for property environment. In Chef 13 this will become an error: Option environment must be a kind of [String]!  You passed {"PATH"=>"/usr/local/bin:/usr/bin:/bin"}.. at /Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/poise-2.6.0/lib/poise/helpers/lazy_default.rb:57:in `set_or_return' at /Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
.[2016-03-23T17:22:42-07:00] WARN: Default value {"PATH"=>"/usr/local/bin:/usr/bin:/bin"} is invalid for property environment. In Chef 13 this will become an error: Option environment must be a kind of [String]!  You passed {"PATH"=>"/usr/local/bin:/usr/bin:/bin"}.. at /Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/poise-2.6.0/lib/poise/helpers/lazy_default.rb:57:in `set_or_return' at /Users/user/github/chef-consul/.bundle/ruby/2.2.0/gems/chef-12.8.1/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
..............

Finished in 1 minute 56.46 seconds (files took 9.41 seconds to load)
19 examples, 0 failures

Randomized with seed 60655

Coverage report generated for Unit Tests to /Users/user/github/chef-consul/coverage. 3339 / 5737 LOC (58.2%) covered.
$
```

**Comment by shortdudey123** [comment]
@johnbellone any update on this from your end? if you retrigger the travis build it should pass

**Comment by shortdudey123** [comment]
@johnbellone web ui tests pass correctly now, windows ones need a bit more changes to pass so i thought i would let you handle part of that to your liking

**Pull request merged**
