### PR TITLE
add dev_mode config option

### PR DESCRIPTION
**Pull request by spheromak**
This option was added to consul 6.

---
This change is [Reviewable](https://reviewable.io/reviews/johnbellone/consul-cookbook/289)

### CODE REVIEW

**Comment by spheromak** [comment]
@johnbellone as I am using the current branch in some recent work. I made this PR against install-resource. 

Also I am not sure if we want to add a constraint on the consul version being used to ensure this doesn't leak into an older install. I didn't see another example of this in the current library, and wasn't sure if it is something you consider in scope.

**Comment by johnbellone** [comment]
@spheromak I don't think we yet have a clean way to limit configuration options for a specific version. That is something that I'll need to think a little more about. I have a general idea of how I want to approach refactoring the config resource, but need to finish up on the install one first.

**Comment by johnbellone** [comment]
Would it be possible for you to rebase? I ended up doing so before merging that branch into master last night.

**Comment by spheromak** [comment]
@johnbellone  you want me to reopen after rebase ?

**Comment by johnbellone** [comment]
I added the attribute in the 2.1 release :).

**Pull request closed without merging**
