### PR TITLE
Avoid creating broken link on windows

### PR DESCRIPTION
**Pull request by kamaradclimber**
Change-Id: I45ae9496ab01f2430d056af9b084d0c9e7a91564

### CODE REVIEW

**Comment by legal90** [comment]
I'd recommend using the [built-in helper `windows?`](https://github.com/chef/chef/blob/master/lib/chef/platform/query_helpers.rb#L23) instead:
```ruby
not_if { windows? }
```
That's just a common practice used in this cookbook as well as in Chef Client itself

**Comment by kamaradclimber** [comment]
ok thanks for the tip

**Comment by kamaradclimber** [comment]
done

**Comment by legal90** [comment]
LGTM. I'm gonna merge this PR since the only failed build is ChefSpec, which is not relevant.
@kamaradclimber Thanks for the contribution!

**Pull request merged**
