### PR TITLE
Feature/windows support

### PR DESCRIPTION
**Pull request by cleung2010**
Fixed feature/windows_support to be on a working state against master in addition to some chocolatey tweaks.

A lot of credit to @ramarnat for the initial #119 PR

### CODE REVIEW

**Comment by ramarnat** [comment]
nice!

**Comment by johnbellone** [comment]
@cleung2010 Is this ready to merge?

**Comment by cleung2010** [comment]
Yep!

**Comment by aardestani** [comment]
even though consul metadata has depend 'chcocolatey', my chef run fails as below
uninitialized constant Chef::Node::ChocolateyHelpers

Looks like it can not find the resource ChocolateyHelpers defined in the libraries on chocolatey cookbook

**Comment by aardestani** [comment]
It was because of my chef version upgraded from 11.6.2 to 11.18.6 and the problem went away.

**Comment by johnbellone** [comment]
Please rebase!

**Comment by cleung2010** [comment]
@johnbellone I fixed conflicts with master, should be good to merge now

**Comment by johnbellone** [comment]
We are going to be merging #126 soon. Please take a look at that as it changes the installation for clients.

**Pull request closed without merging**
