### PR TITLE
Bump version for cookbook release.

### PR DESCRIPTION
**Pull request by johnbellone**
/cc @Ginja @legal90

### CODE REVIEW

**Comment by legal90** [comment]
LGTM 👍   
But could you please take a look at https://github.com/johnbellone/consul-cookbook/pull/378 ? It would be good to get it fixed in this release.

**Comment by iliasbertsimas** [comment]
Could we please get #380 in for this release that has relevant config options for consul 0.7.1 ?

**Comment by Ginja** [comment]
👍

**Comment by stenio123** [comment]
Yep, trying to use retry_join_ec2 but it is not available in the supermarket cookbook with version 2.2.0....

**Comment by legal90** [comment]
I've rebased the branch, so we can release v2.3.0 now
ping @johnbellone

**Comment by stenio123** [comment]
👍

**Comment by legal90** [comment]
@johnbellone Thanks! Could you please push the artifact v2.3.0 to the Supermarket?

**Comment by legal90** [comment]
v2.3.0 released: https://supermarket.chef.io/cookbooks/consul/versions/2.3.0

**Pull request merged**
