### PR TITLE
Feature/windows support

### PR DESCRIPTION
**Pull request by ramarnat**
Started working on this for @full360. If there is interest in merging this in I will post updates.

This is currently WIP so no tests are in place.

### CODE REVIEW

**Comment by johnbellone** [comment]
:+1: for me. It's looking good thus far. Keep it going!

**Comment by ramarnat** [comment]
@johnbellone do have a problem if I add the diplomat gem in here with some helpers to get values directly from the consul api?

**Comment by johnbellone** [comment]
@ramarnat No problem.

**Comment by gdavison** [comment]
We would love to have this available. Is there anything I can do to help with the merge conflict or some other way?

**Comment by johnbellone** [comment]
@gdavison If you have time you can open a new pull-request with the fixes.

**Comment by gdavison** [comment]
@johnbellone I've created PR #196 with fixes

**Pull request closed without merging**
