### PR TITLE
Adding the option to modify the permissions on the consul conf.d dire…

### PR DESCRIPTION
**Pull request by MichaelKueller**
…ctory.

### CODE REVIEW

**Comment by MichaelKueller** [comment]
@Ginja could you readd your comments to the pull request please. I wanted to have two seperate pull requests for the two changes I made, as they are not related to each other.

**Comment by legal90** [comment]
@MichaelKueller Could you please give an example of the use case - when people might want to set custom permissions mode for this dir?

**Comment by MichaelKueller** [comment]
@legal90 yes, sure. 
In our case we have a user different than the consul user, that we use to perform deployments. During the deployment this user writes the service_definition_file into /etc/consul/conf.d directory. 
With the current persmissions (0755) this is not possible, as only the consul user could do so. In this case it is very helpful if these permissions are configurable.

**Comment by legal90** [comment]
Thanks, @MichaelKueller! Now it makes sense 👍 

@johnbellone, Do you have any concerns to get it merged?

**Pull request merged**
