### PR TITLE
Fix consul application path on Windows

### PR DESCRIPTION
**Pull request by slavirok**
There was a hard coded Unix path which was being used on Windows Installation.

### CODE REVIEW

**Comment by legal90** [comment]
Hi @slavirok ! Could you please evaluate - what was the issue you have faced with? Do you install Consul from a package (msi?), or just as a binary?
Sharing the recipe code would be great.

**Comment by legal90** [comment]
The `package` provider for `consul_installation` resource has UNIX-specific path just because it doesn't support Windows yet.
The expected behavior for Windows is using the default provider (`binary`), as it is done in `consul::default` recipe:
https://github.com/johnbellone/consul-cookbook/blob/eebc1299cefb6d766218904ea372566cc84bf373/recipes/default.rb#L23-L40

**Comment by slavirok** [comment]
Hi @legal90 
this is my recipe:

```
include_recipe 'consul::default'

consul_service 'consul' do
  notifies :restart, 'service[consul]'
end

service 'consul' do
  action :nothing
end
```

**Comment by legal90** [comment]
@slavirok This recipe looks wrong. You should not call `consul_service` resource since it is already called in `'consul::default'` recipe.

What is the expected behavior? Do you want to **restart** (instead of reload) the `consul` service every time the `/etc/consul/consul.json` is changed?

**Comment by legal90** [comment]
Closing this PR since it's not relevant to the issue described here.

**Pull request closed without merging**
