### PR TITLE
redirect stderr to syslog and do some cosmetical changes

### PR DESCRIPTION
**Pull request by akerekes**
These changes were introduced by #91 (among others). I've split that PR into smaller chunks in hope for easier merge.

### CODE REVIEW

**Comment by johnbellone** [comment]
Please keep in mind that on *most* Linux distributions this is merely a symlink. On Ubuntu I believe that /bin/sh is a symlink to dash by default.

**Comment by akerekes** [comment]
The important changes are lines 1 and 43, bash is needed for stderr redirection, and stderr redirection is needed to avoid losing information dumped to stderr.
The other two changes, line 23 and 44 are just cosmetic, I can remove them if you want.

**Comment by akerekes** [comment]
@johnbellone Did I answer your question?

**Comment by johnbellone** [comment]
Can you please rebase?

**Comment by akerekes** [comment]
I did. This is my first time to rebase a pull request, please verify it whether it looks good, pls.

**Comment by akerekes** [comment]
@johnbellone do you have any estimates when can this PR be merged? Thanks!

**Pull request merged**
