### PR TITLE
Move webui installation to poise-archive

### LINKED ISSUE #377: Move from zipfile to poise-archive broke webui provider
Webui is still using zipfile resource

### PR DESCRIPTION
**Pull request by tanner-bruce**
Add spec for webui suite

Fixes #377

### CODE REVIEW

**Comment by legal90** [comment]
@tanner-bruce Thanks! LGTM.
Then we will be able to fix this spec: 
https://github.com/johnbellone/consul-cookbook/blob/master/test/spec/libraries/consul_installation_webui_spec.rb

**Comment by tanner-bruce** [comment]
@legal90 I added in the missing checksum for 0.7.1 and fixed up the specs. Not sure why the build is failing randomly, it passes locally.

**Comment by legal90** [comment]
It appears the last build job has been failed due to the channel we use to install ChefDK in TravisCI (`chef-current-trusty`). Currently, it installs ChefDK v1.1.3 which looks unstable.

**Comment by legal90** [comment]
Quote from the Chef slack chat, about this TravisCI build failure:

> I just spun up Chef-DK 1.1.3 and ran `rspec` in it. Everything was fine. I then checkout out your repo, did a `bundle install`, and then ran `rspec`. It blew up. So there's a conflict between something in your Gemfile and newer versions of Chef-DK

cc @johnbellone

**Comment by legal90** [comment]
JFYI: #382 is gonna fix the TravisCI build failure mentioned above

**Pull request merged**
