### PR TITLE
add statsd support

### PR DESCRIPTION
**Pull request by akerekes**
These changes were introduced by https://github.com/johnbellone/consul-cookbook/pull/91 (among others). I've split that PR into smaller chunks in hope for easier merge.

### CODE REVIEW

**Comment by akerekes** [comment]
I'm trying to run the rspec tests, but I get the following

    consul-cookbook/spec/spec_helper.rb:2:in `require': cannot load such file -- chefspec/berkshelf (LoadError)
	from /home/adminuser/akerekes_checkout/consul-cookbook/spec/spec_helper.rb:2:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `require'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `block in requires='
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `each'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `requires='
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:103:in `block in process_options_into'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `each'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `process_options_into'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:95:in `setup'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /var/lib/gems/1.9.1/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from bin/rspec:16:in `load'
	from bin/rspec:16:in `<main>'

Any ideas how to fix this?

**Comment by akerekes** [comment]
I've rebased this pull request too in hope that it will be merged sooner.

**Comment by akerekes** [comment]
@johnbellone do you have an estimate when can this PR be merged? Thanks!

**Comment by adgaudio** [comment]
+1 would be really great to merge this so we can hook consul up with our statsd server!

**Pull request merged**
