### PR TITLE
Windows fixes for 3 0 0

### PR DESCRIPTION
**Pull request by gdavison**
When a master ACL is set on the cluster, the service reload requires the ACL token; this is now added to the Windows service as well.

I've added Windows 2016 to the testing suite, as well as using Matt Wrock's Vagrant boxes as the default for Windows. This means that developers aren't stuck with the choices of rolling their own Windows boxes or skipping testing on Windows.

### CODE REVIEW

**Comment by gdavison** [comment]
Most of the `food critic` failures are in code not touched by this PR

**Comment by gdavison** [comment]
Lol, coverage went **down** when I added tests

**Comment by gdavison** [comment]
@legal90, any chance you could take a look at this? It's blocking ACL use on Windows.

**Comment by legal90** [comment]
@gdavison Thank you! LGTM

**Pull request merged**
