### PR TITLE
Consul Watch: Ignore owner/group on windows machines 

### PR DESCRIPTION
**Pull request by jirkafajfr**
Same owner/group strategy as in https://github.com/johnbellone/consul-cookbook/blob/master/libraries/consul_definition.rb.

### CODE REVIEW

**Comment by majormoses** [comment]
imho it would be better to have the reverse, as windows is the edge case not *nix something like unless windows...

**Comment by jirkafajfr** [comment]
@majormoses I totally agree. I just wanted to be consistent with rest of cookbook. I modified other places with linux condition to the same ```unless Chef::Platform.windows?```

**Comment by Ginja** [comment]
Since we're including the helper library, you can use this method:

https://github.com/johnbellone/consul-cookbook/blob/master/libraries/helpers.rb#L18

```ruby
unless windows?
      owner new_resource.owner
      group new_resource.group
      mode '0640'
end
```

**Comment by majormoses** [comment]
good call on using the helper library functions I hadn't looked at that

**Comment by jirkafajfr** [comment]
done ..

**Comment by jirkafajfr** [comment]
Hi,
do you have any date for next supermarket release?

Thanks

**Comment by legal90** [comment]
@Ginja @jarosser06 
`windows?` helper is not included to `Chef::Resource` :

```
           ================================================================================
           Error executing action `create` on resource 'consul_config[consul]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `windows?' for Chef::Resource::Directory

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/consul/libraries/consul_config.rb:114:in `block (3 levels) in <class:ConsulConfig>'
           /tmp/kitchen/cache/cookbooks/consul/libraries/consul_config.rb:112:in `block (2 levels) in <class:ConsulConfig>'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
           /tmp/kitchen/cache/cookbooks/consul/libraries/consul_config.rb:111:in `block in <class:ConsulConfig>'
```

**Comment by johnbellone** [comment]
`node.platform?('windows')`

**Comment by Ginja** [comment]
To use the helper methods in a resource block you first need to do this:

`Chef::Resource.send(:include, ConsulCookbook::Helpers)`

@johnbellone's solution would work too, as we inject the methods into the Node class:

https://github.com/johnbellone/consul-cookbook/blob/master/libraries/helpers.rb#L147

**Comment by johnbellone** [comment]
This is fixed and released in [2.1.3](https://github.com/johnbellone/consul-cookbook/commit/16d83acb167daee5ab765b977a63eef710296511).

**Pull request merged**
