### PR TITLE
Use config user/group for consul_definition instead of hard coded string

### PR DESCRIPTION
**Pull request by rollbrettler**
Does anything speak against using the `node['consul']['config']['group']` and `node['consul']['config']['user']` value for the default consul_definition attributes?

### CODE REVIEW

**Comment by johnbellone** [comment]
Did you try setting `node['consul']['service_user']` and `node['consul']['service_group']`? I don't really see why you would need to do this with those node attributes.

**Comment by rollbrettler** [comment]
I changed it to `node['consul']['service_user']` and `node['consul']['service_group'] ` but maybe I didn’t fully get your suggestion yet.

**Comment by rollbrettler** [comment]
@johnbellone https://github.com/johnbellone/consul-cookbook/issues/372 is basically what I ran into as well and what I tried to fix with this PR

**Comment by mishak87** [comment]
Watch and service resources are still using hardcoded strings `'consul'`.

https://github.com/johnbellone/consul-cookbook/blob/cd562a7/libraries/consul_watch.rb#L22-L28
https://github.com/johnbellone/consul-cookbook/blob/cd562a7/libraries/consul_service.rb#L24-L31

**Comment by legal90** [comment]
@mishak87 Thanks! Pull-Request #445 fixes that

**Pull request merged**
